### ISSUE TITLE
criterion __init__.py에서 CE loss class가 있는 이유

### ISSUE THREAD

**Issue by papari1123** [boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13#65]
모듈 임포트만 해주는 다른 \_\_init\_\_.py와 다르게, criterion \_\_init\_\_.py에는 CE loss가 직접 명시되어있는데, 어떤 이유일까?

https://github.com/boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13/blob/8d4cdef1b25417653ca568b0af500131ab32160e/criterion/__init__.py#L4-L17

**Comment by intrandom5** [comment]
이건 제가 MLM 구현할 때 썼던 코드... 인데 결국 안 쓰게 돼서 지우는게 맞는데 깜빡했습니다!
이해할 수 없었던 CrossEntropy에 알맞는 input을 넣어주기 위한 노력의 일환이라고 봐주심 됩니다 ㅎㅎ...
그리고 직접 명시되어 있는 것은 어차피 많은 종류가 추가 될 것 같지 않아서 파일을 하나 더 만들기 귀찮았습니다!
