### ISSUE TITLE
utils/trainer.py의 to device 한번에 할당?

### ISSUE THREAD

**Issue by papari1123** [boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13#66]
trainer.py 코드는 원래 train.py에 있던 코드인데, 이걸 따로 빼서 train.py가 클린해졌기 때문에 (이런 수정이) 참 마음에 들었다.

나도 이 코드를 수정하느라 느낀거지만, 좀 더 깔끔하게 고쳤으면 했던 코드는 -> 
- 아래 코드에서 data로 부터 s1, s2, label를 받고 to 메소드를 이용해 device에 할당하고 있다.
- 이 **to 메소드를 변수 별로 사용하는데 조금 지저분해보이는데 한번에 할당하는 방법은 없나?** pytorch lightning은 이런 이슈가 없겠..지?
- 과한 클린 코드 욕구 일수도 있겠다.
https://github.com/boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13/blob/8d4cdef1b25417653ca568b0af500131ab32160e/utils/trainer.py#L7-L10

**Comment by intrandom5** [comment]
for문을 쓰거나 아예 data=data.to(device)로 하면 될 것 같은데...
근데 여기서는 aux가 학습에 전혀 필요없는 인자라서(기록용이죠) aux는 gpu에 할당할 필요가 없기 때문에(자원 낭비) 저거 빼고 s1, s2, label만 gpu에 할당하는게 좋습니다.
그래서 한번에 gpu 할당 하면서 aux를 빼는 코드를 작성하는거나 하나하나 할당해주는 거나 거기서 거기인 것 같은 느낌인데, 직접 할당하는게 더 확실하니까 전 저게 편한 것 같습니다! (당연히 개인 의견이고 취향임. 그리고 aux 없으면 data.to(device)로 하는게 나을 듯.)
그리고 pytorch lightning은 trainer에 인자로 gpu, cpu 선택해주면 저런 과정들 알아서 해주기 때문에 신경 안 써도 됨 편하겠지?
사실 코드 빼면서 trainer.py 구성하는 것도 pytorch lightning에서 train, validation, test step 나눠져 있는 것을 생각하면서 코드를 짰습니다!
