### ISSUE TITLE
[정규표현식] 얼마나 자주 사용하나요? 그리고 속도가 빠른 전처리 방법에 속하는지?

### ISSUE THREAD

**Issue by soohi0** [boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13#67]
https://github.com/boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13/blob/8d4cdef1b25417653ca568b0af500131ab32160e/datasets/data_processing.py#L10

주석처럼 `sentence = re.subn(s+'+',s, sentence)[0]` 한줄로 압축시키고 싶었지만 당시 해결책을 찾지 못해 일단 어거지로 넣은 상태의 코드라 부끄럽습니다.. 

정규 표현식이 익숙하지 않아서 할 때 마다 찾아보는데 찾아봐도 시간이 꽤나 걸립니다. 저만 그런가요?  잘하는 사람은 능숙하게 잘해서 빠르게 하시겠지만.. 데이터 전처리 할 때 정규표현식을 허다하게 많이들 사용하나요? 그리고 추천하는 방법인가요? 사실 다른 방법도 많지만 저 때 정규 표현식을 공부하며 써보자는 마음으로 써본 것이기에 긴가민가하며 썼습니다. 그래서 **시간을 잡고 공부를 할 필요가 있는지** 여부를 여쭙고 싶습니다.

**Comment by intrandom5** [comment]
경험 상 정규표현식 공부해서 작성하는 시간이나 정규표현식을 직접 구현하는 시간이나 비슷하게 드는... 그렇기 때문에 정규 표현식을 공부하는게 좋은 것 같아
나는 정규 표현식을 몰라서 모든 경우의 수를 고려하면서 전처리 코드를 직접 짰었는데 그렇게 짤 시간에 정규표현식 공부 했으면 그 뒤로는 계속 정규 표현식 써서 쉽게 짰겠지? 따로 시간을 못 내더라도 앞으로 전처리코드 작성하면서 필요한 부분이 있으면 그 부분 공부해서 코드 작성하는 식으로 하면 실력이 자연스럽게 늘지 않을까?

**Comment by papari1123** [comment]
열공하자!
