### ISSUE TITLE
0-5 clip과 pearson계수

### ISSUE THREAD

**Issue by risolate** [boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13#71]
https://github.com/boostcampaitech4nlp2/level1_semantictextsimilarity_nlp-level1-nlp-13/blob/2e464bf492b377330e1c139be88f355faad66592/inference.py#L51

끝나고 돌아보면 예측값을 0-5사이로 맞춰줬을 때 pearson이 조금 떨어지는 경우도 존재 했던 것 같습니다.
이유는 pearson의 목적이 값 예측보다는 분포의 비슷함을 보기 때문이라고 생각하는데 혹시 같은 결과를 관측하신 분이 있나요?

**Comment by papari1123** [comment]
(스폐셜 피어세션에서) round를 안했을 때 성능이 올랐다고 한다. (> 경향성을 더 잘 파악한 기존 결과에서 round를 통해 clip했기 때문에 나빠진 듯?
